### ISSUE TITLE
Schematics?

### ISSUE THREAD

**Issue by Jibeji** [AlbertPhan/Airsoft-Chronograph#1]
Hi,
Would you please share the schematics?
Plus, will this work with an Arduino Pro Mini?

**Comment by AlbertPhan** [comment]
Hi i never got a notification for this issue but I added the eagle schematics and board files. It would probably work for the Arduino pro mini but you probably have to do some tweaking. This is not plug and play, you have to know what you are doing. Please note this project was never completely finished. I still have the prototype and it works for most of the features.
